### ISSUE TITLE
determine if gpu is enabled on hub

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-hub#36]
Some containerized spike sorters require an NVIDIA GPU. When these containers are run, SpikeInterface first checks if a user has an NVIDIA GPU installed by running `nvidia-smi`. Googling around indicates this as the best way to determine if a gpu is available. However, this command is not available for dandi hub, even if it does have a GPU available, so the SI command fails with a warning saying that no GPU is present. This is blocking us from running containerized spike sorters on DANDI Hub.

Is there a reason this command does not work in Jupyter? Is there another method via command line or via python to check that a GPU is available? I'd like to keep the concept of checking for a GPU before going through the trouble of pulling a container, and I would be fine with adding some additional check logic that works on DANDI.

**Comment by satra** [comment]
indeed nvidia-smi is not installed and it's unclear if there is a way to do this easily, since the drivers are actually on the node and passed through to the pod. usually the underlying toolkits (tensorflow, pytorch) have a way of estimating this that does not depend on nvidia-smi. i would recommend doing this through that layer. alternatively you can use the `NVIDIA_VISIBLE_DEVICES` environment variable to detect a GPU on DANDI, but this is unlikely to generalize in all environments.

for tensorflow you can use this: `tf.config.list_physical_devices('GPU')`
for pytorch you can use this: `torch.cuda.is_available()` and `torch.cuda.device_count()`

if you are using these toolkits then it should be easier to depend on these.

**Comment by vncntprvst** [comment]
Installing Linux CUDA Toolkit might solve this. This looks similar to the situation on WSL2 (I use WSL for most Linux and Python development). GPU applications on WSL, rely on the NVIDIA Windows GPU Driver. All you need is [installing the CUDA toolkit](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl2), which provides the `nvidia-smi` command.

**Comment by vncntprvst** [comment]
For example, I run Jupyterhub servers from WSL on Windows machines in our lab, to serve data analysis containers with GPU capability to remote users.

**Comment by satra** [comment]
cudatoolkit is installed from conda-forge on the pod container. however, iirc, the nvidia-smi binary only comes with the driver installation, which is not in the pod but on the node OS (if that makes sense). 

matlab must have equivalent ways of detecting the presence of a GPU.

**Comment by samuelgarcia** [comment]
Hi all,
torch will maybe be part of requirement_full.txt quite soon in spikeinterface because lot of work in hackthon depend on it now.
Maybe we can have a machanism of checking GPU either on nvivdia-smi (if available) either on torch (if availalble).
Maybe cudatoolkit offer simpler way to check gpu. I will try to have a look also.

**Comment by satra** [comment]
unfortunately, i don't think nvidia-smi is in that docker image. i think it is somehow brought in from the host driver.

**Comment by satra** [comment]
i did manage to get nvidia-smi installed in the hub docker container. but unfortunately as a pod in kubernetes the command runs into an error:

```
$ nvidia-smi 
Failed to initialize NVML: Driver/library version mismatch
```

i'll try to update things to see if i can remove this mismatch.

**Comment by h-mayorquin** [comment]
Any progress on this?

It seems that torch uses a call to the c-api:
` torch._C._cuda_getDeviceCount() > 0`
(see,  https://pytorch.org/docs/stable/_modules/torch/cuda.html#is_available)

But that attribute is also exposed in the [cuda-python](https://nvidia.github.io/cuda-python/overview.html) package:
https://nvidia.github.io/cuda-python/module/cuda.html#cuda.cuda.cuDeviceGetCount

I tested the following function both in dandi hub and google collab with gpu instances and non-gpu instances and it works:
```
from cuda import cuda

def has_cuda_capable_device():

  try:
    cu_result_init,  = cuda.cuInit(0)
    cu_result, cu_string = cuda.cuGetErrorString(cu_result_init)
    cu_result_device_count, device_count = cuda.cuDeviceGetCount()
    return device_count > 0
  except RuntimeError: #  Failed to dlopen libcuda.so
    return False
    
has_cuda_capable_device()
```

**Comment by satra** [comment]
@h-mayorquin - yes nvidia-smi cannot be accessible in a pod. the only thing you can do is to use an underlying library to get at whether a gpu exists or not:

for tensorflow you can use this: `tf.config.list_physical_devices('GPU')`
for pytorch you can use this: `torch.cuda.is_available()` and `torch.cuda.device_count()`

i'm going to close this for now.

**Comment by h-mayorquin** [comment]
All right, just for the reference of anyone who read this in the future. The library mentioned above should be way less burdensome in an application than either tensorflow or torch.
